feat: add service discovery to the superset service
cds-snc/cds-superset pull request #35
Opened 2024-02-02 21:49 UTC by patheard

# Summary
Update the superset ECS service to include service discovery.

This is being done in preparation for the Celery worker and beat services.

# Related
- https://github.com/cds-snc/platform-core-services/issues/536

2024-02-02 21:59 UTC, CalvinRodo requested changes

2024-02-02 21:59 UTC, CalvinRodo commented on terragrunt/athena_iam.tf
> +      "arn:aws:s3:::4d9f3f22-cff9-4407-ab55-a0d2373b382e/*",
This creates a merge conflict with the current code base, please merge the new changes to the infra.

2024-02-02 22:01 UTC, patheard commented on terragrunt/athena_iam.tf
> +      "arn:aws:s3:::4d9f3f22-cff9-4407-ab55-a0d2373b382e/*",
Done and done my good man

2024-02-05 15:06 UTC, CalvinRodo approved these changes
:taco::cat:

2024-02-05 15:07 UTC, merged